### PR TITLE
[WIP] : QISKIT installer based on setuptools and Cython

### PR DESCRIPTION
**Pull request by nonhermitian**
Provides a standard installation and build chain via setuptools.

## Description
C++ code is compiled via Cython, and linked to the NumPy BLAS libraries automatically.  Support for Windows, and Visual Studio 2015 (the only supported build chain on Windows) comes for free.  The c++ simulators no longer need a PIPE call, and are now called like any other Python object.

## Motivation and Context
Using make is not a standard way of building Python packages.  Instead, this Pull implements the standard `python setup.py install`.  Building the c++ extensions locally, for running unit tests, requires doing `python setup.py build_ext --inplace`, and the resulting binary is built in `qiskit.cython`.  Wheels building is also a simple call: `python setup.py bdist_wheel`.  Going forward, there is a clear path to integration with conda-forge.

This also helps to remedy issues such as #393, #340. 

Benefits over current make process:
- Standard Python package build process; supports building on Windows, in the supported manner, seamlessly.
- Allows for linking c++ code to BLAS from NumPy; Intel MKL or openBLAS binding for free.  Easy testing against multiple BLAS libraries.
- C++ extensions linked and called as standard Python modules.
- C++ exceptions raised to Python exceptions.
- C++ code can be unit tested via Python.
- Removes the hard-coding of `conda` in the install process.
- Easy pushing to Pypi and conda-forge.

## How Has This Been Tested?
So far tested on OSX: Apple clang, HB clang, HB gcc

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [X] All new and existing tests passed.

### CODE REVIEW

**Comment by nonhermitian** [comment]
Note that this will not pass until Travis is reconfigured for new install process.

**Comment by nonhermitian** [comment]
`setup.py` now has commands for `test`, `lint`, `pep8`, `profile` and `coverage`.

**Comment by nonhermitian** [comment]
This has been moved to its own repo so that integration testing is easier to do:

https://github.com/nonhermitian/arrogant_seahorse

**Comment by atilag** [comment]
We are going to restore setup.py file, so anyone can use it directly without having to run cmake first.

**Pull request closed without merging**
