### PR TITLE
Add CLA note in the contributing

### PR DESCRIPTION
**Pull request by abdonrd**
### Summary

Add CLA note requested here: https://github.com/QISKit/qiskit-core/pull/550#issuecomment-395731253

### Details and comments

We also need to activate the CLA.

### CODE REVIEW

**Comment by abdonrd** [comment]
@jaygambetta can you add the `(link to download file)`?

**Comment by jaygambetta** [comment]
@abdonrd working on it.

**Comment by jaygambetta** [comment]
@abdonrd i dont think we need the wip now but we need to make sure the pdf get on qiskit.org.

**Comment by abdonrd** [comment]
@jaygambetta waiting for https://github.com/QISKit/qiskit.org/pull/20

**Pull request merged**
